Fix category names special chars
vtex-apps/rtbhouse pull request #3
Opened 2019-09-24 17:32 UTC by juliomoreira

2019-09-24 17:33 UTC, juliomoreira reviewed
@klzns can you review please?

Thanks,

2019-09-26 18:32 UTC, saviomuniz requested changes

2019-09-26 18:32 UTC, saviofelixmuniz commented on CHANGELOG.md
> +- Fixes category name special chars
```suggestion
- Category name special chars
```

2019-09-26 18:32 UTC, saviofelixmuniz commented on react/helpers/index.tsx
> +  return strNormalized
```suggestion
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
```

2019-09-27 19:40 UTC, saviomuniz approved these changes

2019-09-27 19:41 UTC, merged